In [1]:
import torch

class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

c:\Users\taeyong\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0522, -0.0493,  0.0462,  ..., -0.0590, -0.0924,  0.0640],
        [-0.0518, -0.0091, -0.0404,  ...,  0.0819, -0.0570, -0.0736],
        [ 0.0796,  0.0712,  0.0965,  ...,  0.0196,  0.0518,  0.0074],
        ...,
        [ 0.0774, -0.0157, -0.0623,  ...,  0.0767,  0.0325,  0.0910],
        [ 0.0103,  0.0824, -0.0647,  ...,  0.0551,  0.0260, -0.0538],
        [-0.0476, -0.0027, -0.0020,  ..., -0.0004, -0.0257,  0.0908]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0515,  0.0662,  0.0373, -0.0365,  0.0794, -0.0624, -0.0595,  0.0061,
         0.0371, -0.0127, -0.0774, -0.0009,  0.0996, -0.0827,  0.0903, -0.0265,
         0.0021,  0.0170,  0.0314, -0.07

In [33]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.7409, 0.0510, 0.5069]])


Weight and Bias parameters:
Parameter containing:
tensor([[ 0.2551,  0.2945, -0.5053],
        [ 0.5175, -0.2684,  0.2937]], requires_grad=True)
Parameter containing:
tensor([-0.4646, -0.5663], requires_grad=True)


Output:
tensor([[-0.5167, -0.0477]], grad_fn=<AddmmBackward0>)


In [34]:
import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [35]:
class LSTMTagger(torch.nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

In [36]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.0805, 0.8823, 0.4568, 0.0808, 0.0249, 0.1826],
         [0.7325, 0.9026, 0.9464, 0.5180, 0.0282, 0.1503],
         [0.0733, 0.8582, 0.4195, 0.5514, 0.7293, 0.3175],
         [0.6222, 0.9652, 0.6008, 0.2977, 0.7969, 0.6188],
         [0.7303, 0.9731, 0.2464, 0.4661, 0.6103, 0.6005],
         [0.5436, 0.3059, 0.9323, 0.1104, 0.8357, 0.9149]]])
tensor([[[0.9464, 0.7293],
         [0.9731, 0.9149]]])


In [37]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())

tensor([[[14.6249, 17.8466, 14.9056, 11.0231],
         [ 9.7153, 21.7817,  5.7081, 11.9020],
         [19.5824, 20.7471, 18.0884,  8.6634],
         [24.7661, 12.7220, 12.4863, 21.1029]]])
tensor(15.3541)
tensor([[[ 0.0103,  1.3415,  0.1263, -1.4780],
         [-0.4327,  1.6055, -1.1095, -0.0633],
         [ 0.5890,  0.8329,  0.2761, -1.6980],
         [ 1.3138, -0.9477, -0.9920,  0.6259]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(-8.1956e-08, grad_fn=<MeanBackward0>)


In [38]:
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.0000, 0.0000, 0.4239, 0.0000],
         [0.9084, 0.0000, 0.0000, 1.2953],
         [0.0000, 0.0000, 0.5773, 0.6990],
         [0.7434, 0.0000, 0.7578, 0.0000]]])
tensor([[[0.0000, 1.6165, 0.0000, 0.0000],
         [0.0000, 1.1606, 0.0000, 1.2953],
         [0.9743, 0.0000, 0.5773, 0.0000],
         [0.0000, 0.0000, 0.7578, 1.0485]]])
