In [1]:
import torch

c:\Users\taeyong\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
z = torch.zeros(5, 3)  # make 5x3 tensor filled 0
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [5]:
i = torch.ones((5, 3), dtype=torch.int16)  # make 5x3 tensor filled 1 dtype = int16
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [6]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)  # 2x2 tensor 
print('랜덤 tensor 값:')
print(r1)

r2 = torch.rand(2, 2)  # 2x2 tensor filled random
print('\n다른 랜덤 tensor 값:')
print(r2) # 새로운 2x2 행렬 값

torch.manual_seed(1729)  # seed 고정
r3 = torch.rand(2, 2)
print('\nr1과 일치:')
print(r3) # == r1

랜덤 tensor 값:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

다른 랜덤 tensor 값:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

r1과 일치:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
